### ISSUE TITLE
switch to home assistant v2021.1.5

### ISSUE THREAD

**Issue by theryanb** [Devotics/heatzy-home-hassistant#19]
I switched to version v2021.1.5 and now I can no longer find the entity of my radiator.*
Is the integration suitable for this version?

thanks

**Comment by djk314** [comment]
Sorry it work well need to restart 3 or 4 time.

Host Operating System | Home Assistant OS 5.11
| stable
supervisor-2021.02.6
Version | core-2021.2.3
Supervisor | true
Docker | true
Python | 3.8.7
| Linux
os | 5.4.83-v7

**Comment by Dramloc** [comment]
Hi,
I will close this issue as it seems to be related to #20.

You might also want to try the following project: https://github.com/Cyr-ius/hass-heatzy that is much more maintained and up to date with the latest version of Home Assistant.
