### ISSUE TITLE
'version' key in the manifest file will be mandatory soon

### ISSUE THREAD

**Issue by froggy974** [Devotics/heatzy-home-hassistant#21]
heatzy component will be broken soon :-(

https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes

https://developers.home-assistant.io/docs/creating_integration_manifest/

**Home Assistant details:**
 - Version: 2021.3.2
 - Installation method: Home Assistant OS

Log error message :
```
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 9:29:03 AM (1 occurrences)
Last logged: 9:29:03 AM

No 'version' key in the manifest file for custom integration 'heatzy'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'heatzy' 


is this component is still maintained ?
```

**Comment by Dramloc** [comment]
Hi froggy,

It's becoming complicated for me to maintain this project as I no longer use Heatzy and Home Assistant.
You might want to try the following project: https://github.com/Cyr-ius/hass-heatzy that is much more maintained and up to date with the latest version of Home Assistant.

**Comment by froggy974** [comment]
Je comprends.

Merci pour le lien vers l'alternative ;-)
