### ISSUE TITLE
Problem with HA 0.92 and 0.93

### ISSUE THREAD

**Issue by 5chacha5** [Devotics/heatzy-home-hassistant#3]
Hello since the last update of home assistant 0.92 and 0.93 this custom component didn’t work when I tested it… any update can be found ?

This is my error when I check the config :
 General Errors: 
    - Integration heatzy not found when trying to verify its climate platform.

**Comment by 5chacha5** [comment]
after more searches I think I need a __init__.py. how I can make it ?

**Comment by Dramloc** [comment]
Hello, thanks for letting me know !
I tested the component with 0.93.2 and it seems that adding an empty `__init__.py` fixes it.

Can you let me know if latest version of the component (2.0.1) fixes the issue ?

**Comment by 5chacha5** [comment]
hello

the empty __init__.py fixes the issue !! that work like a charm ;-) thank you !
