### ISSUE TITLE
Possible to use this on Hassio ?

### ISSUE THREAD

**Issue by JulienChafraix** [Devotics/heatzy-home-hassistant#6]
Hello,

More a question than a real issue there, but I was wondering if your project was usable on Hassio, and if so do you have a tutorial to follow ?

I'll do some more tests tomorrow to check that.

Have a nice day !

Julien

**Comment by Dramloc** [comment]
Hello,

I'm not too familiar with Hassio but the following steps seem to work for this plugin (and maybe other custom components):
- Install Hassio
- Install the [SSH Server plugin](https://www.home-assistant.io/addons/ssh/) and configure SSH connection (ssh key or password)
- Connect to Hassio using SSH:
```bash
ssh root@hassio.local
# or ssh root@<hassio ip>
```
- Install the component:
```bash
# Create custom_components folder
mkdir -p /config/custom_components
# Move to the custom_components folder
cd /config/custom_components
# Fetch this repo and extract it
curl -L https://api.github.com/repos/Devotics/heatzy-home-hassistant/tarball/master | tar -xz
# Copy climate folder
cp -rl Devotics-heatzy-home-hassistant-*/heatzy .
# Clean up
rm -rf Devotics-heatzy-home-hassistant-*
```
- Configure the component by editing `/config/configuration.yaml` and adding the following lines:
```yaml
climate:
  - platform: heatzy
    username: <your heatzy email>
    password: <your heatzy password>
```

Let me know if this works!

**Comment by cbastienbaron** [comment]
that's work on Hassio, thanks a lot @Dramloc  

But only input select with different presets works. When i change thermostat slider, error occur; i know heatzy know only 3 orders, but i think a different  view will be better ? WDYT ,

**Comment by Dramloc** [comment]
Hello @cbastienbaron,
I agree, it's not the best user experience right now.

Last time I checked, it was not possible to change this behavior for climate components. I will take a look at the latest releases of HA to see if this can be fixed or if there are simpler components.

I will close this issue and create a new one to keep you updated.
